#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SOURCE="$ROOT/native/aspy"
STATE_ROOT="${SPIKINGJELLY_NPU_ASPY_BUILD_ROOT:-}"
if [[ -z "$STATE_ROOT" ]]; then
  echo "SPIKINGJELLY_NPU_ASPY_BUILD_ROOT must name an external, empty build directory" >&2
  exit 2
fi
mkdir -p "$STATE_ROOT"
STATE_ROOT="$(cd "$STATE_ROOT" && pwd)"
case "$STATE_ROOT/" in
  "$ROOT/"*)
    echo "AsPy build state must remain outside the source repository" >&2
    exit 2
    ;;
esac
if find "$STATE_ROOT" -mindepth 1 -maxdepth 1 -print -quit | grep -q .; then
  echo "refusing to overwrite non-empty AsPy build directory: $STATE_ROOT" >&2
  exit 2
fi

: "${ASCEND_TOOLKIT_HOME:?source the qualified CANN environment first}"
MSOPGEN="${MSOPGEN:-$ASCEND_TOOLKIT_HOME/python/site-packages/bin/msopgen}"
if [[ ! -x "$MSOPGEN" ]]; then
  MSOPGEN="$(command -v msopgen || true)"
fi
if [[ -z "$MSOPGEN" || ! -x "$MSOPGEN" ]]; then
  echo "msopgen was not found in the qualified CANN environment" >&2
  exit 2
fi

PROJECT="$STATE_ROOT/project"
BUILD="$STATE_ROOT/op-build"
INSTALL="$STATE_ROOT/op-install"
BRIDGE_SOURCE="$STATE_ROOT/bridge-source"
BRIDGE_BUILD="$STATE_ROOT/bridge-build"
ENV_FILE="$STATE_ROOT/activate_aspy.sh"

"$MSOPGEN" gen \
  -i "$SOURCE/definition/aspy_if_forward.json" \
  -f aclnn \
  -c ai_core-ascend910b \
  -out "$PROJECT" \
  -op AsPyIfForward \
  -lan cpp
"$MSOPGEN" gen \
  -i "$SOURCE/definition/aspy_if_forward.json" \
  -f aclnn \
  -c ai_core-ascend910b \
  -out "$PROJECT" \
  -m 1 \
  -op AsPyIfBackward \
  -lan cpp
"$MSOPGEN" gen \
  -i "$SOURCE/definition/aspy_lif_forward.json" \
  -f aclnn \
  -c ai_core-ascend910b \
  -out "$PROJECT" \
  -m 1 \
  -op AsPyLifForward \
  -lan cpp
"$MSOPGEN" gen \
  -i "$SOURCE/definition/aspy_lif_forward.json" \
  -f aclnn \
  -c ai_core-ascend910b \
  -out "$PROJECT" \
  -m 1 \
  -op AsPyLifBackward \
  -lan cpp
"$MSOPGEN" gen \
  -i "$SOURCE/definition/aspy_plif_forward.json" \
  -f aclnn \
  -c ai_core-ascend910b \
  -out "$PROJECT" \
  -m 1 \
  -op AsPyPlifForward \
  -lan cpp
"$MSOPGEN" gen \
  -i "$SOURCE/definition/aspy_plif_forward.json" \
  -f aclnn \
  -c ai_core-ascend910b \
  -out "$PROJECT" \
  -m 1 \
  -op AsPyPlifBackward \
  -lan cpp
install -m 0644 "$SOURCE/op_host/as_py_if_forward.cpp" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_if_forward_tiling.h" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_if_backward.cpp" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_if_backward_tiling.h" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_lif_forward.cpp" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_lif_forward_tiling.h" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_lif_backward.cpp" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_lif_backward_tiling.h" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_plif_forward.cpp" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_plif_forward_tiling.h" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_plif_backward.cpp" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_host/as_py_plif_backward_tiling.h" "$PROJECT/op_host/"
install -m 0644 "$SOURCE/op_kernel/as_py_if_forward.cpp" "$PROJECT/op_kernel/"
install -m 0644 "$SOURCE/op_kernel/as_py_if_backward.cpp" "$PROJECT/op_kernel/"
install -m 0644 "$SOURCE/op_kernel/as_py_lif_forward.cpp" "$PROJECT/op_kernel/"
install -m 0644 "$SOURCE/op_kernel/as_py_lif_backward.cpp" "$PROJECT/op_kernel/"
install -m 0644 "$SOURCE/op_kernel/as_py_plif_forward.cpp" "$PROJECT/op_kernel/"
install -m 0644 "$SOURCE/op_kernel/as_py_plif_backward.cpp" "$PROJECT/op_kernel/"
install -m 0644 "$SOURCE/op_kernel/CMakeLists.txt" "$PROJECT/op_kernel/"

cmake -S "$PROJECT" -B "$BUILD" \
  -DASCEND_COMPUTE_UNIT=ascend910b \
  -DCMAKE_INSTALL_PREFIX="$INSTALL" \
  -DASCEND_CANN_PACKAGE_PATH="$ASCEND_TOOLKIT_HOME"
cmake --build "$BUILD" --target install -- -j

mkdir -p "$BRIDGE_SOURCE"
install -m 0644 "$SOURCE/bridge/aspy_bridge.cpp" "$BRIDGE_SOURCE/"
install -m 0644 "$SOURCE/bridge/setup.py" "$BRIDGE_SOURCE/"
(
  cd "$BRIDGE_SOURCE"
  SPIKINGJELLY_NPU_ASPY_OP_API="$INSTALL/op_api" \
    python setup.py build --build-base "$BRIDGE_BUILD"
)
EXTENSION_DIR="$(dirname "$(find "$BRIDGE_BUILD" -type f -name '_spikingjelly_npu_aspy*.so' -print -quit)")"
if [[ -z "$EXTENSION_DIR" || ! -d "$EXTENSION_DIR" ]]; then
  echo "AsPy bridge build did not produce the expected extension" >&2
  exit 1
fi

cat >"$ENV_FILE" <<EOF
# Generated by scripts/build_aspy.sh; source after scripts/cann_env.sh.
export PYTHONPATH="$ROOT/src:$EXTENSION_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
export LD_LIBRARY_PATH="$INSTALL/op_api/lib:$ASCEND_TOOLKIT_HOME/aarch64-linux/lib64\${LD_LIBRARY_PATH:+:\$LD_LIBRARY_PATH}"
export SPIKINGJELLY_NPU_ASPY_EXPECT_NATIVE=1
EOF
chmod 0600 "$ENV_FILE"
printf 'AsPy build completed. Source %s after the CANN environment.\n' "$ENV_FILE"
